/**
 * @packageDocumentation
 * @module api.functional.dashboard_profile.favourite
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
export * as add from "./add";
export * as remove from "./remove";
