/**
 * @packageDocumentation
 * @module api.functional.dashboard.list_all
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
import type { IConnection } from "@nestia/fetcher";
import type { IListEntitiesRequestIDashboard } from "../../../structures/IListEntitiesRequestIDashboard";
import type { IListEntitiesResponseIDashboard } from "../../../structures/IListEntitiesResponseIDashboard";
/**
 * @controller DashboardController.listAll
 * @path POST /dashboard/list-all
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export declare function listAll(connection: IConnection, inputs: listAll.Input): Promise<listAll.Output>;
export declare namespace listAll {
    type Input = IListEntitiesRequestIDashboard;
    type Output = IListEntitiesResponseIDashboard;
    const METADATA: {
        readonly method: "POST";
        readonly path: "/dashboard/list-all";
        readonly request: {
            readonly type: "application/json";
            readonly encrypted: false;
        };
        readonly response: {
            readonly type: "application/json";
            readonly encrypted: false;
        };
        readonly status: 201;
    };
    const path: () => string;
}
