/**
 * @packageDocumentation
 * @module api.functional.image.version.list
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
import type { IConnection } from "@nestia/fetcher";
import type { IListImageVersionRequest } from "../../../../structures/IListImageVersionRequest";
/**
 * @controller ImageController.listVersion
 * @path POST /image/version/list
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export declare function listVersion(connection: IConnection, inputs: listVersion.Input): Promise<listVersion.Output>;
export declare namespace listVersion {
    type Input = IListImageVersionRequest;
    type Output = any[];
    const METADATA: {
        readonly method: "POST";
        readonly path: "/image/version/list";
        readonly request: {
            readonly type: "application/json";
            readonly encrypted: false;
        };
        readonly response: {
            readonly type: "application/json";
            readonly encrypted: false;
        };
        readonly status: 201;
    };
    const path: () => string;
}
