/**
 * @packageDocumentation
 * @module api.functional.dashboard_profile
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
import type { IConnection } from "@nestia/fetcher";
export * as set_default_dashboard from "./set_default_dashboard";
export * as favourite from "./favourite";
/**
 * @controller DashboardProfileController.get
 * @path GET /dashboard-profile/get
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export declare function get(connection: IConnection): Promise<get.Output>;
export declare namespace get {
    type Output = any;
    const METADATA: {
        readonly method: "GET";
        readonly path: "/dashboard-profile/get";
        readonly request: null;
        readonly response: {
            readonly type: "application/json";
            readonly encrypted: false;
        };
        readonly status: 200;
    };
    const path: () => string;
}
