/**
 * @packageDocumentation
 * @module api.functional.query_search_data
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

/**
 * @controller AppController.querySearchData
 * @path POST /query-search-data
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function querySearchData(
  connection: IConnection,
  data: querySearchData.Input,
): Promise<querySearchData.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...querySearchData.METADATA,
      template: querySearchData.METADATA.path,
      path: querySearchData.path(),
    },
    data,
  );
}
export namespace querySearchData {
  export type Input = any;
  export type Output = any;

  export const METADATA = {
    method: "POST",
    path: "/query-search-data",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/query-search-data";
}
