/**
 * @packageDocumentation
 * @module api.functional.image
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

import type { IListImageRequest } from "../../structures/IListImageRequest";

export * as get from "./get";
export * as version from "./version";
export * as category from "./category";
export * as cve from "./cve";

/**
 * @controller ImageController.list
 * @path POST /image/list
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function list(
  connection: IConnection,
  inputs: list.Input,
): Promise<list.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...list.METADATA,
      template: list.METADATA.path,
      path: list.path(),
    },
    inputs,
  );
}
export namespace list {
  export type Input = IListImageRequest;
  export type Output = any[];

  export const METADATA = {
    method: "POST",
    path: "/image/list",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/image/list";
}
