/**
 * @packageDocumentation
 * @module api.functional.image.version.packages
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
import type { IConnection } from "@nestia/fetcher";
/**
 * @controller ImageController.getPackagesByImageVersionId
 * @path POST /image/version/packages
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export declare function getPackagesByImageVersionId(connection: IConnection, inputs: getPackagesByImageVersionId.Input): Promise<getPackagesByImageVersionId.Output>;
export declare namespace getPackagesByImageVersionId {
    type Input = {
        imageVersionId: string;
    };
    type Output = any[];
    const METADATA: {
        readonly method: "POST";
        readonly path: "/image/version/packages";
        readonly request: {
            readonly type: "application/json";
            readonly encrypted: false;
        };
        readonly response: {
            readonly type: "application/json";
            readonly encrypted: false;
        };
        readonly status: 201;
    };
    const path: () => string;
}
