/**
 * @packageDocumentation
 * @module api.functional.image.cve.get
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

import type { IGetImageByIdRequest } from "../../../../structures/IGetImageByIdRequest";

/**
 * @controller ImageController.getCVE
 * @path POST /image/cve/get
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getCVE(
  connection: IConnection,
  inputs: getCVE.Input,
): Promise<getCVE.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...getCVE.METADATA,
      template: getCVE.METADATA.path,
      path: getCVE.path(),
    },
    inputs,
  );
}
export namespace getCVE {
  export type Input = IGetImageByIdRequest;
  export type Output = any;

  export const METADATA = {
    method: "POST",
    path: "/image/cve/get",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/image/cve/get";
}
