/**
 * @packageDocumentation
 * @module api.functional.image.cve.get
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
import type { IConnection } from "@nestia/fetcher";
import type { IGetImageByIdRequest } from "../../../../structures/IGetImageByIdRequest";
/**
 * @controller ImageController.getCVE
 * @path POST /image/cve/get
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export declare function getCVE(connection: IConnection, inputs: getCVE.Input): Promise<getCVE.Output>;
export declare namespace getCVE {
    type Input = IGetImageByIdRequest;
    type Output = any;
    const METADATA: {
        readonly method: "POST";
        readonly path: "/image/cve/get";
        readonly request: {
            readonly type: "application/json";
            readonly encrypted: false;
        };
        readonly response: {
            readonly type: "application/json";
            readonly encrypted: false;
        };
        readonly status: 201;
    };
    const path: () => string;
}
