/**
 * @packageDocumentation
 * @module api.functional.image.version.get
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
import type { IConnection } from "@nestia/fetcher";
/**
 * @controller ImageController.getVersion
 * @path POST /image/version/get
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export declare function getVersion(connection: IConnection, inputs: getVersion.Input): Promise<getVersion.Output>;
export declare namespace getVersion {
    type Input = {
        id: string;
    };
    type Output = any;
    const METADATA: {
        readonly method: "POST";
        readonly path: "/image/version/get";
        readonly request: {
            readonly type: "application/json";
            readonly encrypted: false;
        };
        readonly response: {
            readonly type: "application/json";
            readonly encrypted: false;
        };
        readonly status: 201;
    };
    const path: () => string;
}
