/**
 * @packageDocumentation
 * @module api.functional.get_user_details
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

/**
 * @controller AppController.getUserDetails
 * @path POST /get-user-details
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getUserDetails(
  connection: IConnection,
  data: getUserDetails.Input,
): Promise<getUserDetails.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...getUserDetails.METADATA,
      template: getUserDetails.METADATA.path,
      path: getUserDetails.path(),
    },
    data,
  );
}
export namespace getUserDetails {
  export type Input = {
    session_id: string;
  };
  export type Output = any;

  export const METADATA = {
    method: "POST",
    path: "/get-user-details",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/get-user-details";
}
