/**
 * @packageDocumentation
 * @module api.functional.image.category.list
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

/**
 * @controller ImageController.listCategory
 * @path POST /image/category/list
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function listCategory(
  connection: IConnection,
): Promise<listCategory.Output> {
  return PlainFetcher.fetch(connection, {
    ...listCategory.METADATA,
    template: listCategory.METADATA.path,
    path: listCategory.path(),
  });
}
export namespace listCategory {
  export type Output = any[];

  export const METADATA = {
    method: "POST",
    path: "/image/category/list",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/image/category/list";
}
