/**
 * @packageDocumentation
 * @module api.functional.image.cve.list
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

import type { IListImageCVERequest } from "../../../../structures/IListImageCVERequest";

/**
 * @controller ImageController.listCVE
 * @path POST /image/cve/list
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function listCVE(
  connection: IConnection,
  inputs: listCVE.Input,
): Promise<listCVE.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...listCVE.METADATA,
      template: listCVE.METADATA.path,
      path: listCVE.path(),
    },
    inputs,
  );
}
export namespace listCVE {
  export type Input = IListImageCVERequest;
  export type Output = any[];

  export const METADATA = {
    method: "POST",
    path: "/image/cve/list",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/image/cve/list";
}
