/**
 * @packageDocumentation
 * @module api.functional.dashboard.list.threat_intel
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

import type { IListEntitiesRequestIDashboard } from "../../../../structures/IListEntitiesRequestIDashboard";
import type { IListEntitiesResponseIDashboard } from "../../../../structures/IListEntitiesResponseIDashboard";

/**
 * @controller DashboardController.listThreatIntel
 * @path POST /dashboard/list/threat-intel
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function listThreatIntel(
  connection: IConnection,
  inputs: listThreatIntel.Input,
): Promise<listThreatIntel.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...listThreatIntel.METADATA,
      template: listThreatIntel.METADATA.path,
      path: listThreatIntel.path(),
    },
    inputs,
  );
}
export namespace listThreatIntel {
  export type Input = IListEntitiesRequestIDashboard;
  export type Output = IListEntitiesResponseIDashboard;

  export const METADATA = {
    method: "POST",
    path: "/dashboard/list/threat-intel",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/dashboard/list/threat-intel";
}
