/**
 * @packageDocumentation
 * @module api.functional.open_search.get_fields
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
import type { IConnection } from "@nestia/fetcher";
/**
 * @controller OpenSearchController.getFields
 * @path POST /open-search/get-fields
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export declare function getFields(connection: IConnection): Promise<getFields.Output>;
export declare namespace getFields {
    type Output = any;
    const METADATA: {
        readonly method: "POST";
        readonly path: "/open-search/get-fields";
        readonly request: null;
        readonly response: {
            readonly type: "application/json";
            readonly encrypted: false;
        };
        readonly status: 201;
    };
    const path: () => string;
}
