/**
 * @packageDocumentation
 * @module api.functional.image.category.get
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

import type { IGetImageByIdRequest } from "../../../../structures/IGetImageByIdRequest";

/**
 * @controller ImageController.getCategory
 * @path POST /image/category/get
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getCategory(
  connection: IConnection,
  inputs: getCategory.Input,
): Promise<getCategory.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...getCategory.METADATA,
      template: getCategory.METADATA.path,
      path: getCategory.path(),
    },
    inputs,
  );
}
export namespace getCategory {
  export type Input = IGetImageByIdRequest;
  export type Output = any;

  export const METADATA = {
    method: "POST",
    path: "/image/category/get",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/image/category/get";
}
