/**
 * @packageDocumentation
 * @module api.functional.image.version.get
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

/**
 * @controller ImageController.getVersion
 * @path POST /image/version/get
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getVersion(
  connection: IConnection,
  inputs: getVersion.Input,
): Promise<getVersion.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...getVersion.METADATA,
      template: getVersion.METADATA.path,
      path: getVersion.path(),
    },
    inputs,
  );
}
export namespace getVersion {
  export type Input = {
    id: string;
  };
  export type Output = any;

  export const METADATA = {
    method: "POST",
    path: "/image/version/get",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/image/version/get";
}
