/**
 * @packageDocumentation
 * @module api.functional.open_search
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

import type { IGetQueryDataFilter } from "../../structures/IGetQueryDataFilter";

export * as process_tree from "./process_tree";
export * as get_field_values from "./get_field_values";
export * as get_fields from "./get_fields";

/**
 * @controller OpenSearchController.search
 * @path POST /open-search/search
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function search(
  connection: IConnection,
  query: search.Input,
): Promise<search.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...search.METADATA,
      template: search.METADATA.path,
      path: search.path(),
    },
    query,
  );
}
export namespace search {
  export type Input = IGetQueryDataFilter;
  export type Output = any;

  export const METADATA = {
    method: "POST",
    path: "/open-search/search",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/open-search/search";
}

/**
 * @controller OpenSearchController.alerts
 * @path POST /open-search/alerts
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function alerts(
  connection: IConnection,
  query: alerts.Input,
): Promise<alerts.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...alerts.METADATA,
      template: alerts.METADATA.path,
      path: alerts.path(),
    },
    query,
  );
}
export namespace alerts {
  export type Input = IGetQueryDataFilter;
  export type Output = any;

  export const METADATA = {
    method: "POST",
    path: "/open-search/alerts",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/open-search/alerts";
}
