/**
 * @packageDocumentation
 * @module api.functional.auth.get_user_details
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
import type { IConnection } from "@nestia/fetcher";
/**
 * @controller AuthController.getUserDetails
 * @path GET /auth/get-user-details
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export declare function getUserDetails(connection: IConnection): Promise<getUserDetails.Output>;
export declare namespace getUserDetails {
    type Output = any;
    const METADATA: {
        readonly method: "GET";
        readonly path: "/auth/get-user-details";
        readonly request: null;
        readonly response: {
            readonly type: "application/json";
            readonly encrypted: false;
        };
        readonly status: 200;
    };
    const path: () => string;
}
