/**
 * @packageDocumentation
 * @module api.functional.open_search.get_fields
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

/**
 * @controller OpenSearchController.getFields
 * @path POST /open-search/get-fields
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getFields(
  connection: IConnection,
): Promise<getFields.Output> {
  return PlainFetcher.fetch(connection, {
    ...getFields.METADATA,
    template: getFields.METADATA.path,
    path: getFields.path(),
  });
}
export namespace getFields {
  export type Output = any;

  export const METADATA = {
    method: "POST",
    path: "/open-search/get-fields",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/open-search/get-fields";
}
