/**
 * @packageDocumentation
 * @module api.functional.image.get
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
import type { IConnection } from "@nestia/fetcher";
import type { IGetImageByIdRequest } from "../../../structures/IGetImageByIdRequest";
export * as by_name from "./by_name";
/**
 * @controller ImageController.get
 * @path POST /image/get
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export declare function get(connection: IConnection, inputs: get.Input): Promise<get.Output>;
export declare namespace get {
    type Input = IGetImageByIdRequest;
    type Output = any;
    const METADATA: {
        readonly method: "POST";
        readonly path: "/image/get";
        readonly request: {
            readonly type: "application/json";
            readonly encrypted: false;
        };
        readonly response: {
            readonly type: "application/json";
            readonly encrypted: false;
        };
        readonly status: 201;
    };
    const path: () => string;
}
