/**
 * @packageDocumentation
 * @module api.functional.dashboard.list.threat_intel
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
import type { IConnection } from "@nestia/fetcher";
import type { IListEntitiesRequestIDashboard } from "../../../../structures/IListEntitiesRequestIDashboard";
import type { IListEntitiesResponseIDashboard } from "../../../../structures/IListEntitiesResponseIDashboard";
/**
 * @controller DashboardController.listThreatIntel
 * @path POST /dashboard/list/threat-intel
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export declare function listThreatIntel(connection: IConnection, inputs: listThreatIntel.Input): Promise<listThreatIntel.Output>;
export declare namespace listThreatIntel {
    type Input = IListEntitiesRequestIDashboard;
    type Output = IListEntitiesResponseIDashboard;
    const METADATA: {
        readonly method: "POST";
        readonly path: "/dashboard/list/threat-intel";
        readonly request: {
            readonly type: "application/json";
            readonly encrypted: false;
        };
        readonly response: {
            readonly type: "application/json";
            readonly encrypted: false;
        };
        readonly status: 201;
    };
    const path: () => string;
}
