/**
 * @packageDocumentation
 * @module api.functional.dashboard_profile.set_default_dashboard
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

import type { ISetDefaultDashbordRequest } from "../../../structures/ISetDefaultDashbordRequest";

/**
 * @controller DashboardProfileController.setDefaultDashboard
 * @path POST /dashboard-profile/set-default-dashboard
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function setDefaultDashboard(
  connection: IConnection,
  inputs: setDefaultDashboard.Input,
): Promise<setDefaultDashboard.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...setDefaultDashboard.METADATA,
      template: setDefaultDashboard.METADATA.path,
      path: setDefaultDashboard.path(),
    },
    inputs,
  );
}
export namespace setDefaultDashboard {
  export type Input = ISetDefaultDashbordRequest;
  export type Output = any;

  export const METADATA = {
    method: "POST",
    path: "/dashboard-profile/set-default-dashboard",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/dashboard-profile/set-default-dashboard";
}
