/**
 * @packageDocumentation
 * @module api.functional.dashboard_profile.favourite.remove
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

import type { IAddToFavouriteRequest } from "../../../../structures/IAddToFavouriteRequest";

/**
 * @controller DashboardProfileController.removeFromFavourite
 * @path POST /dashboard-profile/favourite/remove
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function removeFromFavourite(
  connection: IConnection,
  inputs: removeFromFavourite.Input,
): Promise<removeFromFavourite.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...removeFromFavourite.METADATA,
      template: removeFromFavourite.METADATA.path,
      path: removeFromFavourite.path(),
    },
    inputs,
  );
}
export namespace removeFromFavourite {
  export type Input = IAddToFavouriteRequest;
  export type Output = any;

  export const METADATA = {
    method: "POST",
    path: "/dashboard-profile/favourite/remove",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/dashboard-profile/favourite/remove";
}
