/**
 * @packageDocumentation
 * @module api.functional.query_search_data
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
import type { IConnection } from "@nestia/fetcher";
/**
 * @controller AppController.querySearchData
 * @path POST /query-search-data
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export declare function querySearchData(connection: IConnection, data: querySearchData.Input): Promise<querySearchData.Output>;
export declare namespace querySearchData {
    type Input = any;
    type Output = any;
    const METADATA: {
        readonly method: "POST";
        readonly path: "/query-search-data";
        readonly request: {
            readonly type: "application/json";
            readonly encrypted: false;
        };
        readonly response: {
            readonly type: "application/json";
            readonly encrypted: false;
        };
        readonly status: 201;
    };
    const path: () => string;
}
