/**
 * @packageDocumentation
 * @module api.functional
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
import type { IConnection } from "@nestia/fetcher";
export * as get_user_details from "./get_user_details";
export * as query_search_data from "./query_search_data";
export * as open_search from "./open_search";
export * as dashboard_profile from "./dashboard_profile";
export * as role from "./role";
export * as auth from "./auth";
export * as dashboard_category from "./dashboard_category";
export * as dashboard from "./dashboard";
export * as widget from "./widget";
export * as user_variable from "./user_variable";
export * as image from "./image";
/**
 * @controller AppController.getHello
 * @path GET /
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export declare function getHello(connection: IConnection): Promise<getHello.Output>;
export declare namespace getHello {
    type Output = string;
    const METADATA: {
        readonly method: "GET";
        readonly path: "/";
        readonly request: null;
        readonly response: {
            readonly type: "application/json";
            readonly encrypted: false;
        };
        readonly status: 200;
    };
    const path: () => string;
}
