/**
 * @packageDocumentation
 * @module api.functional.image.version.packages
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

/**
 * @controller ImageController.getPackagesByImageVersionId
 * @path POST /image/version/packages
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getPackagesByImageVersionId(
  connection: IConnection,
  inputs: getPackagesByImageVersionId.Input,
): Promise<getPackagesByImageVersionId.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...getPackagesByImageVersionId.METADATA,
      template: getPackagesByImageVersionId.METADATA.path,
      path: getPackagesByImageVersionId.path(),
    },
    inputs,
  );
}
export namespace getPackagesByImageVersionId {
  export type Input = {
    imageVersionId: string;
  };
  export type Output = any[];

  export const METADATA = {
    method: "POST",
    path: "/image/version/packages",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/image/version/packages";
}
