/**
 * @packageDocumentation
 * @module api.functional.image.category.list
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
import type { IConnection } from "@nestia/fetcher";
/**
 * @controller ImageController.listCategory
 * @path POST /image/category/list
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export declare function listCategory(connection: IConnection): Promise<listCategory.Output>;
export declare namespace listCategory {
    type Output = any[];
    const METADATA: {
        readonly method: "POST";
        readonly path: "/image/category/list";
        readonly request: null;
        readonly response: {
            readonly type: "application/json";
            readonly encrypted: false;
        };
        readonly status: 201;
    };
    const path: () => string;
}
