/**
 * @packageDocumentation
 * @module api.functional.image.version.list
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

import type { IListImageVersionRequest } from "../../../../structures/IListImageVersionRequest";

/**
 * @controller ImageController.listVersion
 * @path POST /image/version/list
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function listVersion(
  connection: IConnection,
  inputs: listVersion.Input,
): Promise<listVersion.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...listVersion.METADATA,
      template: listVersion.METADATA.path,
      path: listVersion.path(),
    },
    inputs,
  );
}
export namespace listVersion {
  export type Input = IListImageVersionRequest;
  export type Output = any[];

  export const METADATA = {
    method: "POST",
    path: "/image/version/list",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/image/version/list";
}
