/**
 * @packageDocumentation
 * @module api.functional.dashboard_profile.favourite.remove
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
import type { IConnection } from "@nestia/fetcher";
import type { IAddToFavouriteRequest } from "../../../../structures/IAddToFavouriteRequest";
/**
 * @controller DashboardProfileController.removeFromFavourite
 * @path POST /dashboard-profile/favourite/remove
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export declare function removeFromFavourite(connection: IConnection, inputs: removeFromFavourite.Input): Promise<removeFromFavourite.Output>;
export declare namespace removeFromFavourite {
    type Input = IAddToFavouriteRequest;
    type Output = any;
    const METADATA: {
        readonly method: "POST";
        readonly path: "/dashboard-profile/favourite/remove";
        readonly request: {
            readonly type: "application/json";
            readonly encrypted: false;
        };
        readonly response: {
            readonly type: "application/json";
            readonly encrypted: false;
        };
        readonly status: 201;
    };
    const path: () => string;
}
