/**
 * @packageDocumentation
 * @module api.functional.dashboard_profile.favourite.add
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
import type { IConnection } from "@nestia/fetcher";
import type { IAddToFavouriteRequest } from "../../../../structures/IAddToFavouriteRequest";
/**
 * @controller DashboardProfileController.addToFavourite
 * @path POST /dashboard-profile/favourite/add
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export declare function addToFavourite(connection: IConnection, inputs: addToFavourite.Input): Promise<addToFavourite.Output>;
export declare namespace addToFavourite {
    type Input = IAddToFavouriteRequest;
    type Output = any;
    const METADATA: {
        readonly method: "POST";
        readonly path: "/dashboard-profile/favourite/add";
        readonly request: {
            readonly type: "application/json";
            readonly encrypted: false;
        };
        readonly response: {
            readonly type: "application/json";
            readonly encrypted: false;
        };
        readonly status: 201;
    };
    const path: () => string;
}
