/**
 * @packageDocumentation
 * @module api.functional.image.get.by_name
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

import type { IGetImageByNameRequest } from "../../../../structures/IGetImageByNameRequest";

/**
 * @controller ImageController.getbyName
 * @path POST /image/get/by-name
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getbyName(
  connection: IConnection,
  inputs: getbyName.Input,
): Promise<getbyName.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...getbyName.METADATA,
      template: getbyName.METADATA.path,
      path: getbyName.path(),
    },
    inputs,
  );
}
export namespace getbyName {
  export type Input = IGetImageByNameRequest;
  export type Output = any;

  export const METADATA = {
    method: "POST",
    path: "/image/get/by-name",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/image/get/by-name";
}
