/**
 * @packageDocumentation
 * @module api.functional.auth.get_user_details
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

/**
 * @controller AuthController.getUserDetails
 * @path GET /auth/get-user-details
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getUserDetails(
  connection: IConnection,
): Promise<getUserDetails.Output> {
  return PlainFetcher.fetch(connection, {
    ...getUserDetails.METADATA,
    template: getUserDetails.METADATA.path,
    path: getUserDetails.path(),
  });
}
export namespace getUserDetails {
  export type Output = any;

  export const METADATA = {
    method: "GET",
    path: "/auth/get-user-details",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/auth/get-user-details";
}
