/**
 * @packageDocumentation
 * @module api.functional.image.cve.list
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
import type { IConnection } from "@nestia/fetcher";
import type { IListImageCVERequest } from "../../../../structures/IListImageCVERequest";
/**
 * @controller ImageController.listCVE
 * @path POST /image/cve/list
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export declare function listCVE(connection: IConnection, inputs: listCVE.Input): Promise<listCVE.Output>;
export declare namespace listCVE {
    type Input = IListImageCVERequest;
    type Output = any[];
    const METADATA: {
        readonly method: "POST";
        readonly path: "/image/cve/list";
        readonly request: {
            readonly type: "application/json";
            readonly encrypted: false;
        };
        readonly response: {
            readonly type: "application/json";
            readonly encrypted: false;
        };
        readonly status: 201;
    };
    const path: () => string;
}
