/**
 * @packageDocumentation
 * @module api.functional.dashboard.list
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
import type { IConnection } from "@nestia/fetcher";
import type { IListEntitiesRequestIDashboard } from "../../../structures/IListEntitiesRequestIDashboard";
import type { IListEntitiesResponseIDashboard } from "../../../structures/IListEntitiesResponseIDashboard";
export * as threat_intel from "./threat_intel";
/**
 * @controller DashboardController.list
 * @path POST /dashboard/list
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export declare function list(connection: IConnection, inputs: list.Input): Promise<list.Output>;
export declare namespace list {
    type Input = IListEntitiesRequestIDashboard;
    type Output = IListEntitiesResponseIDashboard;
    const METADATA: {
        readonly method: "POST";
        readonly path: "/dashboard/list";
        readonly request: {
            readonly type: "application/json";
            readonly encrypted: false;
        };
        readonly response: {
            readonly type: "application/json";
            readonly encrypted: false;
        };
        readonly status: 201;
    };
    const path: () => string;
}
