/**
 * @packageDocumentation
 * @module api.functional.open_search.get_field_values
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
import type { IConnection } from "@nestia/fetcher";
/**
 * @controller OpenSearchController.getFieldValues
 * @path POST /open-search/get-field-values
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export declare function getFieldValues(connection: IConnection, query: getFieldValues.Input): Promise<getFieldValues.Output>;
export declare namespace getFieldValues {
    type Input = {
        field: string;
    };
    type Output = any;
    const METADATA: {
        readonly method: "POST";
        readonly path: "/open-search/get-field-values";
        readonly request: {
            readonly type: "application/json";
            readonly encrypted: false;
        };
        readonly response: {
            readonly type: "application/json";
            readonly encrypted: false;
        };
        readonly status: 201;
    };
    const path: () => string;
}
