/**
 * @packageDocumentation
 * @module api.functional
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

export * as get_user_details from "./get_user_details";
export * as query_search_data from "./query_search_data";
export * as open_search from "./open_search";
export * as dashboard_profile from "./dashboard_profile";
export * as role from "./role";
export * as auth from "./auth";
export * as dashboard_category from "./dashboard_category";
export * as dashboard from "./dashboard";
export * as widget from "./widget";
export * as user_variable from "./user_variable";
export * as image from "./image";

/**
 * @controller AppController.getHello
 * @path GET /
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getHello(
  connection: IConnection,
): Promise<getHello.Output> {
  return PlainFetcher.fetch(connection, {
    ...getHello.METADATA,
    template: getHello.METADATA.path,
    path: getHello.path(),
  });
}
export namespace getHello {
  export type Output = string;

  export const METADATA = {
    method: "GET",
    path: "/",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/";
}
