/**
 * @packageDocumentation
 * @module api.functional.open_search.get_field_values
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

/**
 * @controller OpenSearchController.getFieldValues
 * @path POST /open-search/get-field-values
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getFieldValues(
  connection: IConnection,
  query: getFieldValues.Input,
): Promise<getFieldValues.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...getFieldValues.METADATA,
      template: getFieldValues.METADATA.path,
      path: getFieldValues.path(),
    },
    query,
  );
}
export namespace getFieldValues {
  export type Input = {
    field: string;
  };
  export type Output = any;

  export const METADATA = {
    method: "POST",
    path: "/open-search/get-field-values",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/open-search/get-field-values";
}
