/**
 * @packageDocumentation
 * @module api.functional.dashboard_profile.set_default_dashboard
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
import type { IConnection } from "@nestia/fetcher";
import type { ISetDefaultDashbordRequest } from "../../../structures/ISetDefaultDashbordRequest";
/**
 * @controller DashboardProfileController.setDefaultDashboard
 * @path POST /dashboard-profile/set-default-dashboard
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export declare function setDefaultDashboard(connection: IConnection, inputs: setDefaultDashboard.Input): Promise<setDefaultDashboard.Output>;
export declare namespace setDefaultDashboard {
    type Input = ISetDefaultDashbordRequest;
    type Output = any;
    const METADATA: {
        readonly method: "POST";
        readonly path: "/dashboard-profile/set-default-dashboard";
        readonly request: {
            readonly type: "application/json";
            readonly encrypted: false;
        };
        readonly response: {
            readonly type: "application/json";
            readonly encrypted: false;
        };
        readonly status: 201;
    };
    const path: () => string;
}
