/**
 * @packageDocumentation
 * @module api.functional.image
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
import type { IConnection } from "@nestia/fetcher";
import type { IListImageRequest } from "../../structures/IListImageRequest";
export * as get from "./get";
export * as version from "./version";
export * as category from "./category";
export * as cve from "./cve";
/**
 * @controller ImageController.list
 * @path POST /image/list
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export declare function list(connection: IConnection, inputs: list.Input): Promise<list.Output>;
export declare namespace list {
    type Input = IListImageRequest;
    type Output = any[];
    const METADATA: {
        readonly method: "POST";
        readonly path: "/image/list";
        readonly request: {
            readonly type: "application/json";
            readonly encrypted: false;
        };
        readonly response: {
            readonly type: "application/json";
            readonly encrypted: false;
        };
        readonly status: 201;
    };
    const path: () => string;
}
