/**
 * @packageDocumentation
 * @module api.functional.get_user_details
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
import type { IConnection } from "@nestia/fetcher";
/**
 * @controller AppController.getUserDetails
 * @path POST /get-user-details
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export declare function getUserDetails(connection: IConnection, data: getUserDetails.Input): Promise<getUserDetails.Output>;
export declare namespace getUserDetails {
    type Input = {
        session_id: string;
    };
    type Output = any;
    const METADATA: {
        readonly method: "POST";
        readonly path: "/get-user-details";
        readonly request: {
            readonly type: "application/json";
            readonly encrypted: false;
        };
        readonly response: {
            readonly type: "application/json";
            readonly encrypted: false;
        };
        readonly status: 201;
    };
    const path: () => string;
}
