/**
 * @packageDocumentation
 * @module api.functional.dashboard_profile
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

export * as set_default_dashboard from "./set_default_dashboard";
export * as favourite from "./favourite";

/**
 * @controller DashboardProfileController.get
 * @path GET /dashboard-profile/get
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function get(connection: IConnection): Promise<get.Output> {
  return PlainFetcher.fetch(connection, {
    ...get.METADATA,
    template: get.METADATA.path,
    path: get.path(),
  });
}
export namespace get {
  export type Output = any;

  export const METADATA = {
    method: "GET",
    path: "/dashboard-profile/get",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/dashboard-profile/get";
}
