/**
 * @packageDocumentation
 * @module api.functional.auth
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
import type { IConnection } from "@nestia/fetcher";
export * as get_user_details from "./get_user_details";
/**
 * @controller AuthController.logout
 * @path POST /auth/logout
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export declare function logout(connection: IConnection): Promise<logout.Output>;
export declare namespace logout {
    type Output = any;
    const METADATA: {
        readonly method: "POST";
        readonly path: "/auth/logout";
        readonly request: null;
        readonly response: {
            readonly type: "application/json";
            readonly encrypted: false;
        };
        readonly status: 201;
    };
    const path: () => string;
}
