/**
 * @packageDocumentation
 * @module api.functional.dashboard.list_all
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

import type { IListEntitiesRequestIDashboard } from "../../../structures/IListEntitiesRequestIDashboard";
import type { IListEntitiesResponseIDashboard } from "../../../structures/IListEntitiesResponseIDashboard";

/**
 * @controller DashboardController.listAll
 * @path POST /dashboard/list-all
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function listAll(
  connection: IConnection,
  inputs: listAll.Input,
): Promise<listAll.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...listAll.METADATA,
      template: listAll.METADATA.path,
      path: listAll.path(),
    },
    inputs,
  );
}
export namespace listAll {
  export type Input = IListEntitiesRequestIDashboard;
  export type Output = IListEntitiesResponseIDashboard;

  export const METADATA = {
    method: "POST",
    path: "/dashboard/list-all",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/dashboard/list-all";
}
